name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username sorinboia --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sorinboia/scraper:latest
    - name: Push the Docker image
      run: docker push sorinboia/scraper:latest
